---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
#      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /home/patrick/jellyfin/config:/config
      - /home/patrick/jellyfin/series:/data/tvshows
    ports:
      - 8096:8096
#      - 8920:8920 #optional
#      - 7359:7359/udp #optional
#      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
