services:
  mysql:
    restart: unless-stopped
    image: mysql:8.4
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: ${dbuser}
      SEMAPHORE_DB_PASS: ${dbpassword}
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${adminpassword}
      SEMAPHORE_ADMIN_NAME: Patrick Lankhorst
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: ${admin}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${encrkey}
      TZ: Europe/Amsterdam
    depends_on:
      - mysql
volumes:
  semaphore-mysql:
